Fragments
dmersiyanov/LoftMoneyTracker pull request #5
Opened 2017-06-28 08:04 UTC by dmersiyanov

Прошел по всем комментариям, все активности корректно собираются.
Exercise #2 - AddActivity
Exercise #3 - MainActivity
Exercise #4 - FragmentActivity

2017-06-28 19:27 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/FragmentActivity.java
> +public class FragmentActivity extends AppCompatActivity {
Это должна быть MainActivity

2017-06-28 19:27 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/FragmentActivity.java
> +            if (position == 2) args.putString("type", Item.TYPE_INCOME);
тебе тут не нужно проверять позицию у тебя есть массив, можно оттуда взять по позиции тип

2017-06-28 19:27 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/MainActivity.java
>  public class MainActivity extends AppCompatActivity {
Я так понимаю эта активити не нужна вообще. Переименую FragmentsActivity в MainActivity а эту удали.

2017-06-28 19:27 UTC, shushper commented on app/src/main/res/layout/activity_add.xml
> +        <EditText
Так и не сделал, чтобы цена заполнялась справа налево?

2017-06-28 19:27 UTC, shushper commented on app/src/main/res/layout/item.xml
> +        android:layout_marginBottom="0dp"
вот это что за ерунда?

2017-06-28 19:51 UTC, dmersiyanov commented on app/src/main/res/layout/activity_add.xml
> +        <EditText
Сделал. Скинул скрины в слак.

2017-06-28 19:54 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/MainActivity.java
>  public class MainActivity extends AppCompatActivity {
Это же первое задание. Почему она не нужна?

2017-06-28 19:56 UTC, dmersiyanov commented on app/src/main/res/layout/item.xml
> +        android:layout_marginBottom="0dp"
Это пытался сделать, чтобы верний оступ на RecyclerView был больше чем внутренний(между пунктами). 
Я не совсем понимаю, что значит твой коментарий.

2017-06-29 04:17 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/FragmentActivity.java
> +public class FragmentActivity extends AppCompatActivity {
Переименовал.

2017-06-29 04:26 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/FragmentActivity.java
> +            if (position == 2) args.putString("type", Item.TYPE_INCOME);
Вот тут не совсем понял как работает. Исправил в след. комите

2017-06-29 04:32 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/MainActivity.java
>  public class MainActivity extends AppCompatActivity {
Переименовал в RecyclerActivity

2017-06-29 04:38 UTC, dmersiyanov commented on app/src/main/res/layout/item.xml
> +        android:layout_marginBottom="0dp"
Не знаю, что ты имел ввиду, но кажется поправил.

2017-06-29 21:18 UTC, shushper requested changes

2017-06-29 21:18 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/MainActivity.java
> +        getSupportActionBar().setElevation(0);
Круто конечно хакнул систему))) + за находчивость. Но потом нужно будет убрать, когда пройдёте как Toolbar в разметку добавлять. Пока оставь.

2017-06-29 21:18 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/MainActivity.java
> +            args.putString("type", types[position]);
Вут тот вот разберись и оставь одну из этих строчек)

2017-06-29 21:18 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/BalanceFragment.java
> +    private String type;
Я понимаю, что скопипастил. Но вот зачем тебе тут эти два филда? Убери.

2017-06-29 21:18 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/Item.java
> +    private final String[] types = {"expense",
Вот тут зачем этот массив?

2017-06-29 21:18 UTC, shushper commented on app/src/main/java/com/example/mitya/loftmoneytracker/RecyclerActivity.java
> +public class RecyclerActivity extends AppCompatActivity {
Ну ты же вынес весь код отсюда в ItemsFragment. Ну вот зачем тебе эта активити?)

2017-06-29 21:18 UTC, shushper commented on app/src/main/res/layout/activity_add.xml
> +        <EditText
В общем магия. Ты сделал не как надо, но работает))) Сойдёт. Ты чисто из-за wrap_content выехал.  Обычно все задавали ширину вроде в 60dp и ставили либо gravity, либо кто-то ещё находил какой-то параметр. Вроде textAlign. Если работает можешь так оставить.

2017-06-29 21:18 UTC, shushper commented on app/src/main/res/layout/activity_fragments.xml
> +<?xml version="1.0" encoding="utf-8"?>
Вот кстати ты активити переивеновал в MainActivity, значит и разметку этого экрана нужно соотвественно назвать activity_main.

2017-06-29 21:18 UTC, shushper commented on app/src/main/res/layout/item.xml
> +        android:layout_marginBottom="0dp"
В общем задавать margin равный 0 вроде как бессмысленно. Он и так 0 по умолчанию. Я вот у тебя удалил и не заметил чтобы что-то поломалось.

2017-06-29 21:18 UTC, shushper commented on app/src/main/res/layout/items.xml
> +    android:padding="@dimen/margin_l"
Может убрать тут паддинги? Как-то прям много лишенго простарнства по ощущениям. Посмотрел в оригинальном приложении, там нет этих паддингов. Лучше убрать.

2017-06-30 08:41 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/MainActivity.java
> +            args.putString("type", types[position]);
оставил эту args.putString("type", types[position]);

2017-06-30 08:50 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/BalanceFragment.java
> +    private String type;
Убрал.

2017-06-30 08:54 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/Item.java
> +    private final String[] types = {"expense",
Убрал.

2017-06-30 08:55 UTC, dmersiyanov commented on app/src/main/java/com/example/mitya/loftmoneytracker/RecyclerActivity.java
> +public class RecyclerActivity extends AppCompatActivity {
удалил)

2017-06-30 09:05 UTC, dmersiyanov commented on app/src/main/res/layout/activity_fragments.xml
> +<?xml version="1.0" encoding="utf-8"?>
Переименовал.

2017-06-30 09:07 UTC, dmersiyanov commented on app/src/main/res/layout/items.xml
> +    android:padding="@dimen/margin_l"
Уменьшил до 10dp кажется так оптимально по дизайну.

2017-07-04 06:54 UTC, merged